jobs:
  include:
    - name: python 2.7
      language: python
      python: 2.7
      sudo: false
      install: pip install tox-travis
      before_script: cd $TRAVIS_BUILD_DIR/python
      script: tox

    - name: python 3.5
      language: python
      python: 3.5
      sudo: false
      install: pip install tox-travis
      before_script: cd $TRAVIS_BUILD_DIR/python
      script: tox

    - name: python 3.6
      language: python
      python: 3.6
      sudo: false
      install: pip install tox-travis
      before_script: cd $TRAVIS_BUILD_DIR/python
      script: tox

    - name: python 3.7
      language: python
      python: 3.7
      sudo: true
      dist: xenial
      install: pip install tox-travis
      before_script: cd $TRAVIS_BUILD_DIR/python
      script: tox

    - name: Vim (vader)
      language: csharp
      sudo: true
      mono: none
      dotnet: 3.1.402
      env:
        - VIM_VERSION=8.2.1000
        - VIM_VERSION=8.2.0000
        - VIM_VERSION=8.1.0000
        - VIM_VERSION=8.0.0000
        - VIM_VERSION=7.4
      install:
        - installer/omnisharp-manager.sh -l $HOME/.omnisharp/omnisharp-roslyn
        - git clone https://github.com/junegunn/vader.vim.git $TRAVIS_BUILD_DIR/../vader.vim
        - git clone https://github.com/vim/vim
        - (if ! test -d $HOME/vim-$VIM_VERSION/bin; then
            git clone https://github.com/vim/vim $HOME/vim &&
            cd $HOME/vim &&
            git checkout v$VIM_VERSION &&
            ./configure --prefix=$HOME/vim-$VIM_VERSION &&
            make &&
            make install;
          fi)
      before_script: cd test
      script:
        - export PATH=$HOME/vim-$VIM_VERSION/bin:$PATH
        - cd $TRAVIS_BUILD_DIR/test
        - vim -esNu vimrc -c 'Vader! *'
      after_script: cat ../log/*_omnisharp.log
